### ISSUE TITLE
how to run it ?

### ISSUE THREAD

**Issue by tegapaul1944** [AreebE/Chess#1]
hello, i would like to know how to run your game ?

**Comment by AreebE** [comment]
My apologies, I should have been more specific. To run the game, you need to download the code in some IDE, such as Eclipse, IntelliJ, or Replit. When playing a game though, make sure  'debugFileLoader()' is commented out while 'debugGraphics()' is commented in. Please let me know if these instructions are too vague. I'll try to fix the game, keep in mind this is still a work in progress.
